[package]
name = "udp-lib-2"
version = "0.1.0"
edition = "2018"

[lib]
name = "udpl"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[dev-dependencies]
md5 = "0.7.0"

